image:
  file: .gitpod.Dockerfile
tasks:
- command: "cargo build --no-default-features --features \"no-libc\""
- command: "cargo watch -x check"
  openIn: right
  openMode: tab-before
privileged: true
vscode:
  extensions:
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==